### ISSUE TITLE
Warning "StyledLink.styles: null has no effect on ManyToManyField"

### ISSUE THREAD

**Issue by sobolevn** [mkoistinen/djangocms-styledlink#3]
I am using:
```
Django==1.8.7
django-cms==3.2.0
```

> » python manage.py migrate
> /Users/sobolev/.virtualenvs/winestylist/lib/python2.7/site-packages/djangocms_styledlink/models.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
>   from django.contrib.contenttypes import generic
> 
> System check identified some issues:
> 
> WARNINGS:
> djangocms_styledlink.StyledLink.styles: (fields.W340) null has no effect on ManyToManyField.

**Comment by mkoistinen** [comment]
Closed by #4
